### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by mrsalieri** [emregeldegul/tfc#1]
I get error during setup

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import tfc
  File "/Users/folder/tfc-master/tfc/tfc/__init__.py", line 5, in <module>
    from .tfc import Translation
  File "/Users/folder/tfc-master/tfc/tfc/tfc.py", line 36
    Popen(["notify-send", "TFC Result:", f"{recent_value}: {text}"])
                                                                 ^
SyntaxError: invalid syntax

python version 2.7, MacOs 10.14.6

I am not familiar with python so if it is my fault I am sorry for taking your time.

**Comment by emregeldegul** [comment]
Python 2.7 not support f-stirngs. Please, trying with Python 3.6
Also 2x support will expire soon.

**Comment by mrsalieri** [comment]
oh thanks for the info
